version: '2'
services:
    web:
        build:
            context: ./web/
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - "8081:80"
        links:
            - app
    app:
        build:
            context: ./app/
            dockerfile: app.docker
        volumes:
            - ../:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=homestead"
            - "DB_USERNAME=homestead"
            - "DB_PASSWORD=secret"
    database:
        image: mysql:5.7
        volumes:
            - ../docker/database/data:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
        ports:
            - "33061:3306"